# Generated by Django 3.1.6 on 2021-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingID', models.CharField(max_length=100)),
                ('buildingName', models.CharField(max_length=100)),
                ('buildingLocation', models.CharField(max_length=100)),
                ('buildingCapacity', models.CharField(max_length=100)),
                ('numberOfRooms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campusID', models.CharField(max_length=100)),
                ('campusName', models.CharField(max_length=100)),
                ('campusLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentID', models.CharField(max_length=100)),
                ('equipmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(max_length=100)),
                ('roomName', models.CharField(max_length=100)),
                ('roomCapacity', models.CharField(max_length=100)),
            ],
        ),
    ]
