# Generated by Django 3.1.6 on 2021-03-31 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.campus'),
        ),
    ]
