# Generated by Django 3.1.6 on 2021-03-31 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_building_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.building'),
        ),
    ]
