# Generated by Django 3.1.6 on 2021-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210330_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='buildingLocation',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='campusLocation',
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campusID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campusName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
