# Generated by Django 3.1.6 on 2021-04-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20210330_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
