# Generated by Django 3.1.6 on 2021-04-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20210412_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
