# Generated by Django 3.1.6 on 2021-04-12 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_remove_equipment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.room'),
        ),
    ]
