# Generated by Django 3.1.6 on 2021-03-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mustangsID', models.CharField(max_length=100)),
                ('buildingID', models.CharField(max_length=100)),
                ('checkIn', models.CharField(max_length=100)),
                ('scanTime', models.CharField(max_length=100)),
            ],
        ),
    ]
