# Generated by Django 3.1.6 on 2021-03-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='scanDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='scanTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
