# Generated by Django 3.1.6 on 2021-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0003_auto_20210330_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='buildingID',
            field=models.CharField(max_length=100),
        ),
    ]
