# Generated by Django 3.1.6 on 2021-03-31 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20210330_2159'),
        ('qr_scan', '0004_auto_20210330_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkIn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.building'),
        ),
    ]
