# Generated by Django 3.1.6 on 2021-04-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0009_auto_20210331_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='room',
        ),
    ]
