# Generated by Django 3.1.6 on 2021-04-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20210412_1802'),
        ('qr_scan', '0010_remove_checkin_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.room'),
        ),
    ]
