# Generated by Django 3.1.6 on 2021-04-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_scan', '0013_checkin_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='room',
        ),
    ]
